# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import product_pb2 as product__pb2
except ImportError:
    from . import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductGrpcServiceStub:
    """==========================================
    Product gRPC Service Definition
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProducts = channel.unary_unary(
                '/product.ProductGrpcService/GetProducts',
                request_serializer=product__pb2.ProductListRequest.SerializeToString,
                response_deserializer=product__pb2.ProductListResponse.FromString,
                _registered_method=True)
        self.GetProductById = channel.unary_unary(
                '/product.ProductGrpcService/GetProductById',
                request_serializer=product__pb2.ProductDetailRequest.SerializeToString,
                response_deserializer=product__pb2.ProductDetailResponse.FromString,
                _registered_method=True)
        self.GetSellerProducts = channel.unary_unary(
                '/product.ProductGrpcService/GetSellerProducts',
                request_serializer=product__pb2.SellerProductsRequest.SerializeToString,
                response_deserializer=product__pb2.ProductListResponse.FromString,
                _registered_method=True)
        self.GetCategories = channel.unary_unary(
                '/product.ProductGrpcService/GetCategories',
                request_serializer=product__pb2.CategoriesRequest.SerializeToString,
                response_deserializer=product__pb2.CategoriesResponse.FromString,
                _registered_method=True)
        self.GetFilterMeta = channel.unary_unary(
                '/product.ProductGrpcService/GetFilterMeta',
                request_serializer=product__pb2.FilterMetaRequest.SerializeToString,
                response_deserializer=product__pb2.FilterMetaResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/product.ProductGrpcService/CreateProduct',
                request_serializer=product__pb2.CreateProductGrpcRequest.SerializeToString,
                response_deserializer=product__pb2.ProductDetailResponse.FromString,
                _registered_method=True)
        self.DeductStock = channel.unary_unary(
                '/product.ProductGrpcService/DeductStock',
                request_serializer=product__pb2.DeductStockGrpcRequest.SerializeToString,
                response_deserializer=product__pb2.DeductStockGrpcResponse.FromString,
                _registered_method=True)


class ProductGrpcServiceServicer:
    """==========================================
    Product gRPC Service Definition
    ==========================================
    """

    def GetProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilterMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeductStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducts,
                    request_deserializer=product__pb2.ProductListRequest.FromString,
                    response_serializer=product__pb2.ProductListResponse.SerializeToString,
            ),
            'GetProductById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductById,
                    request_deserializer=product__pb2.ProductDetailRequest.FromString,
                    response_serializer=product__pb2.ProductDetailResponse.SerializeToString,
            ),
            'GetSellerProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerProducts,
                    request_deserializer=product__pb2.SellerProductsRequest.FromString,
                    response_serializer=product__pb2.ProductListResponse.SerializeToString,
            ),
            'GetCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategories,
                    request_deserializer=product__pb2.CategoriesRequest.FromString,
                    response_serializer=product__pb2.CategoriesResponse.SerializeToString,
            ),
            'GetFilterMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilterMeta,
                    request_deserializer=product__pb2.FilterMetaRequest.FromString,
                    response_serializer=product__pb2.FilterMetaResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=product__pb2.CreateProductGrpcRequest.FromString,
                    response_serializer=product__pb2.ProductDetailResponse.SerializeToString,
            ),
            'DeductStock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeductStock,
                    request_deserializer=product__pb2.DeductStockGrpcRequest.FromString,
                    response_serializer=product__pb2.DeductStockGrpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductGrpcService:
    """==========================================
    Product gRPC Service Definition
    ==========================================
    """

    @staticmethod
    def GetProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductGrpcService/GetProducts',
            product__pb2.ProductListRequest.SerializeToString,
            product__pb2.ProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductGrpcService/GetProductById',
            product__pb2.ProductDetailRequest.SerializeToString,
            product__pb2.ProductDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductGrpcService/GetSellerProducts',
            product__pb2.SellerProductsRequest.SerializeToString,
            product__pb2.ProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductGrpcService/GetCategories',
            product__pb2.CategoriesRequest.SerializeToString,
            product__pb2.CategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFilterMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductGrpcService/GetFilterMeta',
            product__pb2.FilterMetaRequest.SerializeToString,
            product__pb2.FilterMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductGrpcService/CreateProduct',
            product__pb2.CreateProductGrpcRequest.SerializeToString,
            product__pb2.ProductDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeductStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductGrpcService/DeductStock',
            product__pb2.DeductStockGrpcRequest.SerializeToString,
            product__pb2.DeductStockGrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
