"""alter created_by to string in products

Revision ID: 7511a9271ceb
Revises: 07a556ea0957
Create Date: 2026-09-16 16:58:29.564086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7511a9271ceb'
down_revision: Union[str, Sequence[str], None] = '07a556ea0957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'created_by',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
