"""alter the user fileds

Revision ID: 71fdd7f64224
Revises: 73135eeb3772
Create Date: 2026-09-16 14:26:51.001573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fdd7f64224'
down_revision: Union[str, Sequence[str], None] = '73135eeb3772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum('ADMIN', 'ENDUSER', 'SELLER', name='userrole')
    user_role.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column('role', user_role, server_default='ENDUSER', nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role = sa.Enum('ADMIN', 'ENDUSER', 'SELLER', name='userrole')
    user_role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
