# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import order_pb2 as order__pb2
except ImportError:
    from . import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderGrpcServiceStub:
    """==========================================
    Order gRPC Service Definition
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCart = channel.unary_unary(
                '/order.OrderGrpcService/GetCart',
                request_serializer=order__pb2.CartRequest.SerializeToString,
                response_deserializer=order__pb2.CartResponse.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/order.OrderGrpcService/AddToCart',
                request_serializer=order__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=order__pb2.CartActionResponse.FromString,
                _registered_method=True)
        self.UpdateCartItem = channel.unary_unary(
                '/order.OrderGrpcService/UpdateCartItem',
                request_serializer=order__pb2.UpdateCartItemRequest.SerializeToString,
                response_deserializer=order__pb2.CartActionResponse.FromString,
                _registered_method=True)
        self.DeleteCartItem = channel.unary_unary(
                '/order.OrderGrpcService/DeleteCartItem',
                request_serializer=order__pb2.DeleteCartItemRequest.SerializeToString,
                response_deserializer=order__pb2.CartActionResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/order.OrderGrpcService/ClearCart',
                request_serializer=order__pb2.CartRequest.SerializeToString,
                response_deserializer=order__pb2.CartActionResponse.FromString,
                _registered_method=True)
        self.GetWishlist = channel.unary_unary(
                '/order.OrderGrpcService/GetWishlist',
                request_serializer=order__pb2.WishlistRequest.SerializeToString,
                response_deserializer=order__pb2.WishlistResponse.FromString,
                _registered_method=True)
        self.ToggleWishlist = channel.unary_unary(
                '/order.OrderGrpcService/ToggleWishlist',
                request_serializer=order__pb2.ToggleWishlistRequest.SerializeToString,
                response_deserializer=order__pb2.ToggleWishlistResponse.FromString,
                _registered_method=True)
        self.MoveWishlistToCart = channel.unary_unary(
                '/order.OrderGrpcService/MoveWishlistToCart',
                request_serializer=order__pb2.MoveWishlistRequest.SerializeToString,
                response_deserializer=order__pb2.CartActionResponse.FromString,
                _registered_method=True)
        self.CheckoutOrder = channel.unary_unary(
                '/order.OrderGrpcService/CheckoutOrder',
                request_serializer=order__pb2.CheckoutGrpcRequest.SerializeToString,
                response_deserializer=order__pb2.CheckoutGrpcResponse.FromString,
                _registered_method=True)
        self.GetMyOrders = channel.unary_unary(
                '/order.OrderGrpcService/GetMyOrders',
                request_serializer=order__pb2.MyOrdersRequest.SerializeToString,
                response_deserializer=order__pb2.OrderListResponse.FromString,
                _registered_method=True)
        self.GetOrderById = channel.unary_unary(
                '/order.OrderGrpcService/GetOrderById',
                request_serializer=order__pb2.OrderDetailRequest.SerializeToString,
                response_deserializer=order__pb2.OrderDetailResponse.FromString,
                _registered_method=True)
        self.GetOrderTracking = channel.unary_unary(
                '/order.OrderGrpcService/GetOrderTracking',
                request_serializer=order__pb2.OrderTrackingRequest.SerializeToString,
                response_deserializer=order__pb2.OrderTrackingResponse.FromString,
                _registered_method=True)
        self.ConfirmOrderInternal = channel.unary_unary(
                '/order.OrderGrpcService/ConfirmOrderInternal',
                request_serializer=order__pb2.ConfirmOrderInternalRequest.SerializeToString,
                response_deserializer=order__pb2.ConfirmOrderResponse.FromString,
                _registered_method=True)
        self.FailOrderInternal = channel.unary_unary(
                '/order.OrderGrpcService/FailOrderInternal',
                request_serializer=order__pb2.FailOrderInternalRequest.SerializeToString,
                response_deserializer=order__pb2.FailOrderResponse.FromString,
                _registered_method=True)
        self.GetSellerAnalytics = channel.unary_unary(
                '/order.OrderGrpcService/GetSellerAnalytics',
                request_serializer=order__pb2.SellerAnalyticsRequest.SerializeToString,
                response_deserializer=order__pb2.SellerAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetSellerOrders = channel.unary_unary(
                '/order.OrderGrpcService/GetSellerOrders',
                request_serializer=order__pb2.SellerOrdersRequest.SerializeToString,
                response_deserializer=order__pb2.SellerOrderListResponse.FromString,
                _registered_method=True)
        self.UpdateSellerOrderStatus = channel.unary_unary(
                '/order.OrderGrpcService/UpdateSellerOrderStatus',
                request_serializer=order__pb2.UpdateOrderStatusRequest.SerializeToString,
                response_deserializer=order__pb2.UpdateOrderStatusResponse.FromString,
                _registered_method=True)
        self.GetAdminProfits = channel.unary_unary(
                '/order.OrderGrpcService/GetAdminProfits',
                request_serializer=order__pb2.EmptyOrderRequest.SerializeToString,
                response_deserializer=order__pb2.AdminProfitsResponse.FromString,
                _registered_method=True)
        self.GetAdminSellersSummary = channel.unary_unary(
                '/order.OrderGrpcService/GetAdminSellersSummary',
                request_serializer=order__pb2.EmptyOrderRequest.SerializeToString,
                response_deserializer=order__pb2.AdminSellersSummaryResponse.FromString,
                _registered_method=True)


class OrderGrpcServiceServicer:
    """==========================================
    Order gRPC Service Definition
    ==========================================
    """

    def GetCart(self, request, context):
        """Cart RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCartItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCartItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWishlist(self, request, context):
        """Wishlist RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleWishlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveWishlistToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckoutOrder(self, request, context):
        """Checkout & Customer Orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderTracking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmOrderInternal(self, request, context):
        """Internal Inter-service calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailOrderInternal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerAnalytics(self, request, context):
        """Seller & Admin 5% Engine RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSellerOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminProfits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminSellersSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=order__pb2.CartRequest.FromString,
                    response_serializer=order__pb2.CartResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=order__pb2.AddToCartRequest.FromString,
                    response_serializer=order__pb2.CartActionResponse.SerializeToString,
            ),
            'UpdateCartItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCartItem,
                    request_deserializer=order__pb2.UpdateCartItemRequest.FromString,
                    response_serializer=order__pb2.CartActionResponse.SerializeToString,
            ),
            'DeleteCartItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCartItem,
                    request_deserializer=order__pb2.DeleteCartItemRequest.FromString,
                    response_serializer=order__pb2.CartActionResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=order__pb2.CartRequest.FromString,
                    response_serializer=order__pb2.CartActionResponse.SerializeToString,
            ),
            'GetWishlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWishlist,
                    request_deserializer=order__pb2.WishlistRequest.FromString,
                    response_serializer=order__pb2.WishlistResponse.SerializeToString,
            ),
            'ToggleWishlist': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleWishlist,
                    request_deserializer=order__pb2.ToggleWishlistRequest.FromString,
                    response_serializer=order__pb2.ToggleWishlistResponse.SerializeToString,
            ),
            'MoveWishlistToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveWishlistToCart,
                    request_deserializer=order__pb2.MoveWishlistRequest.FromString,
                    response_serializer=order__pb2.CartActionResponse.SerializeToString,
            ),
            'CheckoutOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckoutOrder,
                    request_deserializer=order__pb2.CheckoutGrpcRequest.FromString,
                    response_serializer=order__pb2.CheckoutGrpcResponse.SerializeToString,
            ),
            'GetMyOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyOrders,
                    request_deserializer=order__pb2.MyOrdersRequest.FromString,
                    response_serializer=order__pb2.OrderListResponse.SerializeToString,
            ),
            'GetOrderById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderById,
                    request_deserializer=order__pb2.OrderDetailRequest.FromString,
                    response_serializer=order__pb2.OrderDetailResponse.SerializeToString,
            ),
            'GetOrderTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderTracking,
                    request_deserializer=order__pb2.OrderTrackingRequest.FromString,
                    response_serializer=order__pb2.OrderTrackingResponse.SerializeToString,
            ),
            'ConfirmOrderInternal': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmOrderInternal,
                    request_deserializer=order__pb2.ConfirmOrderInternalRequest.FromString,
                    response_serializer=order__pb2.ConfirmOrderResponse.SerializeToString,
            ),
            'FailOrderInternal': grpc.unary_unary_rpc_method_handler(
                    servicer.FailOrderInternal,
                    request_deserializer=order__pb2.FailOrderInternalRequest.FromString,
                    response_serializer=order__pb2.FailOrderResponse.SerializeToString,
            ),
            'GetSellerAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerAnalytics,
                    request_deserializer=order__pb2.SellerAnalyticsRequest.FromString,
                    response_serializer=order__pb2.SellerAnalyticsResponse.SerializeToString,
            ),
            'GetSellerOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerOrders,
                    request_deserializer=order__pb2.SellerOrdersRequest.FromString,
                    response_serializer=order__pb2.SellerOrderListResponse.SerializeToString,
            ),
            'UpdateSellerOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSellerOrderStatus,
                    request_deserializer=order__pb2.UpdateOrderStatusRequest.FromString,
                    response_serializer=order__pb2.UpdateOrderStatusResponse.SerializeToString,
            ),
            'GetAdminProfits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminProfits,
                    request_deserializer=order__pb2.EmptyOrderRequest.FromString,
                    response_serializer=order__pb2.AdminProfitsResponse.SerializeToString,
            ),
            'GetAdminSellersSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminSellersSummary,
                    request_deserializer=order__pb2.EmptyOrderRequest.FromString,
                    response_serializer=order__pb2.AdminSellersSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.OrderGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('order.OrderGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderGrpcService:
    """==========================================
    Order gRPC Service Definition
    ==========================================
    """

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetCart',
            order__pb2.CartRequest.SerializeToString,
            order__pb2.CartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/AddToCart',
            order__pb2.AddToCartRequest.SerializeToString,
            order__pb2.CartActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCartItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/UpdateCartItem',
            order__pb2.UpdateCartItemRequest.SerializeToString,
            order__pb2.CartActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCartItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/DeleteCartItem',
            order__pb2.DeleteCartItemRequest.SerializeToString,
            order__pb2.CartActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/ClearCart',
            order__pb2.CartRequest.SerializeToString,
            order__pb2.CartActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWishlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetWishlist',
            order__pb2.WishlistRequest.SerializeToString,
            order__pb2.WishlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleWishlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/ToggleWishlist',
            order__pb2.ToggleWishlistRequest.SerializeToString,
            order__pb2.ToggleWishlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveWishlistToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/MoveWishlistToCart',
            order__pb2.MoveWishlistRequest.SerializeToString,
            order__pb2.CartActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckoutOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/CheckoutOrder',
            order__pb2.CheckoutGrpcRequest.SerializeToString,
            order__pb2.CheckoutGrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetMyOrders',
            order__pb2.MyOrdersRequest.SerializeToString,
            order__pb2.OrderListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetOrderById',
            order__pb2.OrderDetailRequest.SerializeToString,
            order__pb2.OrderDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetOrderTracking',
            order__pb2.OrderTrackingRequest.SerializeToString,
            order__pb2.OrderTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmOrderInternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/ConfirmOrderInternal',
            order__pb2.ConfirmOrderInternalRequest.SerializeToString,
            order__pb2.ConfirmOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailOrderInternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/FailOrderInternal',
            order__pb2.FailOrderInternalRequest.SerializeToString,
            order__pb2.FailOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetSellerAnalytics',
            order__pb2.SellerAnalyticsRequest.SerializeToString,
            order__pb2.SellerAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetSellerOrders',
            order__pb2.SellerOrdersRequest.SerializeToString,
            order__pb2.SellerOrderListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSellerOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/UpdateSellerOrderStatus',
            order__pb2.UpdateOrderStatusRequest.SerializeToString,
            order__pb2.UpdateOrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminProfits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetAdminProfits',
            order__pb2.EmptyOrderRequest.SerializeToString,
            order__pb2.AdminProfitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminSellersSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderGrpcService/GetAdminSellersSummary',
            order__pb2.EmptyOrderRequest.SerializeToString,
            order__pb2.AdminSellersSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
