# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"d\n\x1d\x43reatePaymentOrderGrpcRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\"\xa7\x01\n\x1e\x43reatePaymentOrderGrpcResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x19\n\x11razorpay_order_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x0e\n\x06key_id\x18\x06 \x01(\t\x12\x15\n\rerror_message\x18\x07 \x01(\t\"n\n\x18VerifyPaymentGrpcRequest\x12\x19\n\x11razorpay_order_id\x18\x01 \x01(\t\x12\x1b\n\x13razorpay_payment_id\x18\x02 \x01(\t\x12\x1a\n\x12razorpay_signature\x18\x03 \x01(\t\"\x8a\x01\n\x19VerifyPaymentGrpcResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08order_id\x18\x04 \x01(\t\x12\x12\n\npayment_id\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\"C\n\x18HandleWebhookGrpcRequest\x12\x14\n\x0cpayload_json\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\"c\n\x19HandleWebhookGrpcResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2\xab\x02\n\x12PaymentGrpcService\x12\x65\n\x12\x43reatePaymentOrder\x12&.payment.CreatePaymentOrderGrpcRequest\x1a\'.payment.CreatePaymentOrderGrpcResponse\x12V\n\rVerifyPayment\x12!.payment.VerifyPaymentGrpcRequest\x1a\".payment.VerifyPaymentGrpcResponse\x12V\n\rHandleWebhook\x12!.payment.HandleWebhookGrpcRequest\x1a\".payment.HandleWebhookGrpcResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPAYMENTORDERGRPCREQUEST']._serialized_start=26
  _globals['_CREATEPAYMENTORDERGRPCREQUEST']._serialized_end=126
  _globals['_CREATEPAYMENTORDERGRPCRESPONSE']._serialized_start=129
  _globals['_CREATEPAYMENTORDERGRPCRESPONSE']._serialized_end=296
  _globals['_VERIFYPAYMENTGRPCREQUEST']._serialized_start=298
  _globals['_VERIFYPAYMENTGRPCREQUEST']._serialized_end=408
  _globals['_VERIFYPAYMENTGRPCRESPONSE']._serialized_start=411
  _globals['_VERIFYPAYMENTGRPCRESPONSE']._serialized_end=549
  _globals['_HANDLEWEBHOOKGRPCREQUEST']._serialized_start=551
  _globals['_HANDLEWEBHOOKGRPCREQUEST']._serialized_end=618
  _globals['_HANDLEWEBHOOKGRPCRESPONSE']._serialized_start=620
  _globals['_HANDLEWEBHOOKGRPCRESPONSE']._serialized_end=719
  _globals['_PAYMENTGRPCSERVICE']._serialized_start=722
  _globals['_PAYMENTGRPCSERVICE']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
