# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import user_pb2 as user__pb2
except ImportError:
    from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserGrpcServiceStub:
    """==========================================
    User gRPC Service Definition
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterOrLogin = channel.unary_unary(
                '/user.UserGrpcService/RegisterOrLogin',
                request_serializer=user__pb2.RegisterRequest.SerializeToString,
                response_deserializer=user__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.VerifyOTP = channel.unary_unary(
                '/user.UserGrpcService/VerifyOTP',
                request_serializer=user__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=user__pb2.VerifyOTPResponse.FromString,
                _registered_method=True)
        self.GetUserProfile = channel.unary_unary(
                '/user.UserGrpcService/GetUserProfile',
                request_serializer=user__pb2.UserProfileRequest.SerializeToString,
                response_deserializer=user__pb2.UserProfileResponse.FromString,
                _registered_method=True)
        self.UpdateUserProfile = channel.unary_unary(
                '/user.UserGrpcService/UpdateUserProfile',
                request_serializer=user__pb2.UserUpdateRequest.SerializeToString,
                response_deserializer=user__pb2.UserUpdateResponse.FromString,
                _registered_method=True)
        self.GetAddresses = channel.unary_unary(
                '/user.UserGrpcService/GetAddresses',
                request_serializer=user__pb2.AddressListRequest.SerializeToString,
                response_deserializer=user__pb2.AddressListResponse.FromString,
                _registered_method=True)
        self.AddAddress = channel.unary_unary(
                '/user.UserGrpcService/AddAddress',
                request_serializer=user__pb2.AddAddressRequest.SerializeToString,
                response_deserializer=user__pb2.AddressItemResponse.FromString,
                _registered_method=True)
        self.DeleteAddress = channel.unary_unary(
                '/user.UserGrpcService/DeleteAddress',
                request_serializer=user__pb2.DeleteAddressRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteAddressResponse.FromString,
                _registered_method=True)
        self.RegisterSeller = channel.unary_unary(
                '/user.UserGrpcService/RegisterSeller',
                request_serializer=user__pb2.SellerRegisterRequest.SerializeToString,
                response_deserializer=user__pb2.SellerAuthResponse.FromString,
                _registered_method=True)
        self.SellerAuthOTP = channel.unary_unary(
                '/user.UserGrpcService/SellerAuthOTP',
                request_serializer=user__pb2.SellerAuthOTPRequest.SerializeToString,
                response_deserializer=user__pb2.SellerAuthOTPResponse.FromString,
                _registered_method=True)
        self.SellerVerifyOTP = channel.unary_unary(
                '/user.UserGrpcService/SellerVerifyOTP',
                request_serializer=user__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=user__pb2.SellerAuthResponse.FromString,
                _registered_method=True)
        self.AdminAuthOTP = channel.unary_unary(
                '/user.UserGrpcService/AdminAuthOTP',
                request_serializer=user__pb2.AdminAuthOTPRequest.SerializeToString,
                response_deserializer=user__pb2.AdminAuthOTPResponse.FromString,
                _registered_method=True)
        self.AdminVerifyOTP = channel.unary_unary(
                '/user.UserGrpcService/AdminVerifyOTP',
                request_serializer=user__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=user__pb2.AdminVerifyResponse.FromString,
                _registered_method=True)
        self.GetSellerProfile = channel.unary_unary(
                '/user.UserGrpcService/GetSellerProfile',
                request_serializer=user__pb2.SellerProfileRequest.SerializeToString,
                response_deserializer=user__pb2.SellerProfileResponse.FromString,
                _registered_method=True)
        self.GetAllSellersForAdmin = channel.unary_unary(
                '/user.UserGrpcService/GetAllSellersForAdmin',
                request_serializer=user__pb2.EmptyUserRequest.SerializeToString,
                response_deserializer=user__pb2.SellerListResponse.FromString,
                _registered_method=True)
        self.ToggleSellerStatus = channel.unary_unary(
                '/user.UserGrpcService/ToggleSellerStatus',
                request_serializer=user__pb2.ToggleSellerRequest.SerializeToString,
                response_deserializer=user__pb2.ToggleSellerResponse.FromString,
                _registered_method=True)


class UserGrpcServiceServicer:
    """==========================================
    User gRPC Service Definition
    ==========================================
    """

    def RegisterOrLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSeller(self, request, context):
        """Seller & Admin RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellerAuthOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellerVerifyOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminAuthOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminVerifyOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllSellersForAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleSellerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterOrLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterOrLogin,
                    request_deserializer=user__pb2.RegisterRequest.FromString,
                    response_serializer=user__pb2.RegisterResponse.SerializeToString,
            ),
            'VerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOTP,
                    request_deserializer=user__pb2.VerifyOTPRequest.FromString,
                    response_serializer=user__pb2.VerifyOTPResponse.SerializeToString,
            ),
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=user__pb2.UserProfileRequest.FromString,
                    response_serializer=user__pb2.UserProfileResponse.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=user__pb2.UserUpdateRequest.FromString,
                    response_serializer=user__pb2.UserUpdateResponse.SerializeToString,
            ),
            'GetAddresses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddresses,
                    request_deserializer=user__pb2.AddressListRequest.FromString,
                    response_serializer=user__pb2.AddressListResponse.SerializeToString,
            ),
            'AddAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAddress,
                    request_deserializer=user__pb2.AddAddressRequest.FromString,
                    response_serializer=user__pb2.AddressItemResponse.SerializeToString,
            ),
            'DeleteAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAddress,
                    request_deserializer=user__pb2.DeleteAddressRequest.FromString,
                    response_serializer=user__pb2.DeleteAddressResponse.SerializeToString,
            ),
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=user__pb2.SellerRegisterRequest.FromString,
                    response_serializer=user__pb2.SellerAuthResponse.SerializeToString,
            ),
            'SellerAuthOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.SellerAuthOTP,
                    request_deserializer=user__pb2.SellerAuthOTPRequest.FromString,
                    response_serializer=user__pb2.SellerAuthOTPResponse.SerializeToString,
            ),
            'SellerVerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.SellerVerifyOTP,
                    request_deserializer=user__pb2.VerifyOTPRequest.FromString,
                    response_serializer=user__pb2.SellerAuthResponse.SerializeToString,
            ),
            'AdminAuthOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminAuthOTP,
                    request_deserializer=user__pb2.AdminAuthOTPRequest.FromString,
                    response_serializer=user__pb2.AdminAuthOTPResponse.SerializeToString,
            ),
            'AdminVerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminVerifyOTP,
                    request_deserializer=user__pb2.VerifyOTPRequest.FromString,
                    response_serializer=user__pb2.AdminVerifyResponse.SerializeToString,
            ),
            'GetSellerProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerProfile,
                    request_deserializer=user__pb2.SellerProfileRequest.FromString,
                    response_serializer=user__pb2.SellerProfileResponse.SerializeToString,
            ),
            'GetAllSellersForAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSellersForAdmin,
                    request_deserializer=user__pb2.EmptyUserRequest.FromString,
                    response_serializer=user__pb2.SellerListResponse.SerializeToString,
            ),
            'ToggleSellerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleSellerStatus,
                    request_deserializer=user__pb2.ToggleSellerRequest.FromString,
                    response_serializer=user__pb2.ToggleSellerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.UserGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.UserGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserGrpcService:
    """==========================================
    User gRPC Service Definition
    ==========================================
    """

    @staticmethod
    def RegisterOrLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/RegisterOrLogin',
            user__pb2.RegisterRequest.SerializeToString,
            user__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/VerifyOTP',
            user__pb2.VerifyOTPRequest.SerializeToString,
            user__pb2.VerifyOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/GetUserProfile',
            user__pb2.UserProfileRequest.SerializeToString,
            user__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/UpdateUserProfile',
            user__pb2.UserUpdateRequest.SerializeToString,
            user__pb2.UserUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/GetAddresses',
            user__pb2.AddressListRequest.SerializeToString,
            user__pb2.AddressListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/AddAddress',
            user__pb2.AddAddressRequest.SerializeToString,
            user__pb2.AddressItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/DeleteAddress',
            user__pb2.DeleteAddressRequest.SerializeToString,
            user__pb2.DeleteAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/RegisterSeller',
            user__pb2.SellerRegisterRequest.SerializeToString,
            user__pb2.SellerAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellerAuthOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/SellerAuthOTP',
            user__pb2.SellerAuthOTPRequest.SerializeToString,
            user__pb2.SellerAuthOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellerVerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/SellerVerifyOTP',
            user__pb2.VerifyOTPRequest.SerializeToString,
            user__pb2.SellerAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminAuthOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/AdminAuthOTP',
            user__pb2.AdminAuthOTPRequest.SerializeToString,
            user__pb2.AdminAuthOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminVerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/AdminVerifyOTP',
            user__pb2.VerifyOTPRequest.SerializeToString,
            user__pb2.AdminVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/GetSellerProfile',
            user__pb2.SellerProfileRequest.SerializeToString,
            user__pb2.SellerProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllSellersForAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/GetAllSellersForAdmin',
            user__pb2.EmptyUserRequest.SerializeToString,
            user__pb2.SellerListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleSellerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserGrpcService/ToggleSellerStatus',
            user__pb2.ToggleSellerRequest.SerializeToString,
            user__pb2.ToggleSellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
