# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import payment_pb2 as payment__pb2
except ImportError:
    from . import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentGrpcServiceStub:
    """==========================================
    Payment gRPC Service Definition
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePaymentOrder = channel.unary_unary(
                '/payment.PaymentGrpcService/CreatePaymentOrder',
                request_serializer=payment__pb2.CreatePaymentOrderGrpcRequest.SerializeToString,
                response_deserializer=payment__pb2.CreatePaymentOrderGrpcResponse.FromString,
                _registered_method=True)
        self.VerifyPayment = channel.unary_unary(
                '/payment.PaymentGrpcService/VerifyPayment',
                request_serializer=payment__pb2.VerifyPaymentGrpcRequest.SerializeToString,
                response_deserializer=payment__pb2.VerifyPaymentGrpcResponse.FromString,
                _registered_method=True)
        self.HandleWebhook = channel.unary_unary(
                '/payment.PaymentGrpcService/HandleWebhook',
                request_serializer=payment__pb2.HandleWebhookGrpcRequest.SerializeToString,
                response_deserializer=payment__pb2.HandleWebhookGrpcResponse.FromString,
                _registered_method=True)


class PaymentGrpcServiceServicer:
    """==========================================
    Payment gRPC Service Definition
    ==========================================
    """

    def CreatePaymentOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePaymentOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePaymentOrder,
                    request_deserializer=payment__pb2.CreatePaymentOrderGrpcRequest.FromString,
                    response_serializer=payment__pb2.CreatePaymentOrderGrpcResponse.SerializeToString,
            ),
            'VerifyPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPayment,
                    request_deserializer=payment__pb2.VerifyPaymentGrpcRequest.FromString,
                    response_serializer=payment__pb2.VerifyPaymentGrpcResponse.SerializeToString,
            ),
            'HandleWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleWebhook,
                    request_deserializer=payment__pb2.HandleWebhookGrpcRequest.FromString,
                    response_serializer=payment__pb2.HandleWebhookGrpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentGrpcService:
    """==========================================
    Payment gRPC Service Definition
    ==========================================
    """

    @staticmethod
    def CreatePaymentOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGrpcService/CreatePaymentOrder',
            payment__pb2.CreatePaymentOrderGrpcRequest.SerializeToString,
            payment__pb2.CreatePaymentOrderGrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGrpcService/VerifyPayment',
            payment__pb2.VerifyPaymentGrpcRequest.SerializeToString,
            payment__pb2.VerifyPaymentGrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGrpcService/HandleWebhook',
            payment__pb2.HandleWebhookGrpcRequest.SerializeToString,
            payment__pb2.HandleWebhookGrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
